### ISSUE TITLE
Error al informar CAEA Factura C

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#11]
Hola buen día,

AFIP me devuelve este error al querer informar CAEA de Factura C

`<Code>1443</Code><Msg>Para comprobantes tipo C el objeto IVA no debe informarse.</Msg>`

Encontré un error, cuando quiero armar el objeto el array de IVA es obligatorio en su librería.

Podrían poner la propiedad:

```
val inData = FECAEARegInformativo()
...
inData.feCAEARegInfReq.feDetReq.fecaeaDetRequest[0].iva = ArrayOfAlicIva()
```

Como Opcional? Gracias.

**Comment by lainz** [comment]
```
W/System.err: java.lang.RuntimeException: org.simpleframework.xml.core.ElementException: Value for @org.simpleframework.xml.Element(data=false, name=Iva, required=true, type=void) on field 'iva' protected ar.com.system.afip.wsfe.service.api.ArrayOfAlicIva ar.com.system.afip.wsfe.service.api.FEDetRequest.iva is null in class ar.com.system.afip.wsfe.service.api.FECAEADetRequest
W/System.err:     at retrofit2.converter.simplexml.SimpleXmlRequestBodyConverter.convert(SimpleXmlRequestBodyConverter.java:43)
        at retrofit2.converter.simplexml.SimpleXmlRequestBodyConverter.convert(SimpleXmlRequestBodyConverter.java:26)
        at io.github.nibiruos.retrosoap.RequestConverter.convert(RequestConverter.java:35)
        at io.github.nibiruos.retrosoap.RequestConverter.convert(RequestConverter.java:18)
        at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:355)
        at retrofit2.ServiceMethod.toCall(ServiceMethod.java:110)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
```

**Comment by lainz** [comment]
Poniendo así, required = false, anda bien:

```
@Element(name = "Iva", required = false)
    protected ArrayOfAlicIva iva;
```

Lo unico eso falla los tests, y ahi no tengo idea como cambiarlos.. Pero ya me funciona, podrían agregar ese cambio? Gracias.

**Comment by lbrasseur** [comment]
Dale, si no crea un pull request con este cambio y el otro que mencionaste y vemos de corregir los tests en ese branch.

Gracias!!

**Comment by lainz** [comment]
Listo gracias, ahi hice el pull request

**Comment by lbrasseur** [comment]
Mergeado!
