### ISSUE TITLE
ValueRequiredException, como leer el mensaje enviado por AFIP

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#16]
Tengo el siguiente problema al emitir una Factura A por un cliente que no tiene permitido hacer Factura A.

Este es el error que recibo de la librería:

```
W/System.err: java.lang.RuntimeException: org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(data=false, name=CAE, required=true, type=void) on field 'cae' protected java.lang.String ar.com.system.afip.wsfe.service.api.FECAEDetResponse.cae in class ar.com.system.afip.wsfe.service.api.FECAEDetResponse at line 1
W/System.err:     at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:44)
        at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:23)
        at io.github.nibiruos.retrosoap.ResponseConverter.convert(ResponseConverter.java:96)
        at io.github.nibiruos.retrosoap.ResponseConverter.convert(ResponseConverter.java:18)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
        at ar.com.system.afip.android.wsfe.service.ServiceSoapImpl.fecaeSolicitar(ServiceSoapImpl.java:26)
        at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.lambda$null$0$WsfeManagerImpl(WsfeManagerImpl.java:45)
        at ar.com.system.afip.wsfe.business.impl.-$$Lambda$WsfeManagerImpl$iaB5pe-NI_oFU2PeUIzCCdUdeDE.call(lambda)
        at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.lambda$exception$38(WsfeManagerImpl.java:217)
        at ar.com.system.afip.wsfe.business.impl.-$$Lambda$WsfeManagerImpl$ix4oq-OrwTdhIZu65ZyIuqICA1o.call(lambda)
        at ar.com.system.afip.android.common.service.RetrosoapExceptionConverter.convert(RetrosoapExceptionConverter.java:21)
W/System.err:     at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.exception(WsfeManagerImpl.java:217)
        at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.checkFecaErrors(WsfeManagerImpl.java:212)
        at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.lambda$fecaeSolicitar$1$WsfeManagerImpl(WsfeManagerImpl.java:44)
        at ar.com.system.afip.wsfe.business.impl.-$$Lambda$WsfeManagerImpl$7kgYEm1XSN9eoyhkTE4MwDmT3h4.apply(lambda)
        at ar.com.system.afip.wsaa.business.impl.WsaaTemplateImpl.runAuhtenticated(WsaaTemplateImpl.java:55)
        at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.fecaeSolicitar(WsfeManagerImpl.java:44)
        at com.pos3nstar.posta.ventas.VentaViewModel.facturaElectronica(VentaViewModel.kt:2487)
W/System.err:     at com.pos3nstar.posta.ventas.VentaViewModel.prepararVenta(VentaViewModel.kt:1416)
        at com.pos3nstar.posta.ventas.VentaViewModel.prepararVenta$default(VentaViewModel.kt:1247)
        at com.pos3nstar.posta.ventastablet.VentasTabletActivity$prepararVenta$1.invokeSuspend(VentasTabletActivity.kt:4007)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
W/System.err: Caused by: org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(data=false, name=CAE, required=true, type=void) on field 'cae' protected java.lang.String ar.com.system.afip.wsfe.service.api.FECAEDetResponse.cae in class ar.com.system.afip.wsfe.service.api.FECAEDetResponse at line 1
W/System.err:     at org.simpleframework.xml.core.Composite.readInstance(Composite.java:580)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
W/System.err:     at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
W/System.err:     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
W/System.err:     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
W/System.err:     at org.simpleframework.xml.core.Persister.read(Persister.java:625)
        at org.simpleframework.xml.core.Persister.read(Persister.java:606)
        at org.simpleframework.xml.core.Persister.read(Persister.java:584)
        at org.simpleframework.xml.core.Persister.read(Persister.java:562)
        at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:36)
    	... 28 more
```

Y esto es lo que recibo de AFIP:

`D/OkHttp: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Header><FEHeaderInfo xmlns="http://ar.gov.afip.dif.FEV1/"><ambiente>Produccion - Paa</ambiente><fecha>2022-01-05T20:04:33.7075297-03:00</fecha><id>4.4.0.0</id></FEHeaderInfo></soap:Header><soap:Body><FECAESolicitarResponse xmlns="http://ar.gov.afip.dif.FEV1/"><FECAESolicitarResult><FeCabResp>..........................<Errors><Err><Code>10000</Code><Msg>NO AUTORIZADO A EMITIR COMPROBANTES - LA CUIT INFORMADA NO SE ENCUENTRA AUTORIZADA A EMITIR COMPROBANTES CLASE 'A'</Msg></Err></Errors></FECAESolicitarResult></FECAESolicitarResponse></soap:Body></soap:Envelope>`

Como hago para poder leer el Err Code 10000 NO AUTORIZADO A EMITIR COMPROBANTES - LA CUIT INFORMADA NO SE ENCUENTRA AUTORIZADA A EMITIR COMPROBANTES CLASE 'A', y poder mostrarlo al usuario?

**Comment by lbrasseur** [comment]
Hola, qué tal? Ni idea la verdad, jeje.

Por lo que veo en el log, aparentemente el problema es que el campo `cae` está viniendo vacío (lo cual es lógico, ya que es una respuesta de error) y está marcado como requerido en la clase `ar.com.system.afip.wsfe.service.api.FECAEDetResponse`.

Fijate que en el log menciona la anotación: `@org.simpleframework.xml.Element(data=false, name=CAE, required=true, type=void) on field 'cae'`

Podés probar cambiarle `required` a `false`? Para ver si con eso se arregla.

Se me ocurren 2 posibilidades:
* Que el campo deba ser opcional
* Que la clase utilizada en la respuesta no sea la correcta (que en lugar de usar `FECAEDetResponse` haya que usar otra).

Gracias!

**Comment by lainz** [comment]
Intente poner el campo como opcional pero no se como compilar la librería con IntelliJ Idea Community Edition.
